name: Anchore Enterprise Distributed Scan

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Build'

env:
  ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
  ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
  ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
  ANCHORECTL_FAIL_BASED_ON_RESULTS: false
  REGISTRY: ghcr.io

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Use docker/metadata-action to generate tags (still best practice for consistent tagging)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha,format=long

      # --- DEBUGGING STEP ADDED HERE ---
      - name: Debug - List Files in Workspace and Verify Dockerfile Path
        run: |
          echo "Listing files in the root of the workspace (${{ github.workspace }}):"
          ls -alF ${{ github.workspace }}
          echo ""
          echo "Listing files in .github/workflows directory (just for context):"
          ls -alF ${{ github.workspace }}/.github/workflows/
          echo ""
          echo "Attempting to locate Dockerfile with 'find':"
          find ${{ github.workspace }} -name "Dockerfile" # Case-sensitive find for 'Dockerfile'
          find ${{ github.workspace }} -iname "dockerfile" # Case-insensitive find for 'dockerfile'
          echo ""
          echo "The Dockerfile path being used in the next step is set to: ${{ github.workspace }}/Dockerfile"
      # --- END DEBUGGING STEP ---

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile # Assuming Dockerfile is in the root
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

  Anchore:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: "Set IMAGE environmental variables for Anchore"
        run: |
          REPO_SLUG_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=${{ env.REGISTRY }}/${REPO_SLUG_LOWERCASE}:${{ github.ref_name }}" >> $GITHUB_ENV
          echo "Debug: Anchore IMAGE set to ${{ env.IMAGE }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Latest anchorectl Binary
        run: |
          curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.6.0
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM and Push to Anchore
        run: |
          anchorectl image add --no-auto-subscribe --wait --from registry --dockerfile Dockerfile ${IMAGE}

      - name: Pull Vulnerability List
        run: |
          anchorectl image vulnerabilities ${IMAGE}

      - name: Pull Policy Evaluation
        run: |
          anchorectl image check --detail ${IMAGE}
