name: Anchore Enterprise Distributed Scan

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Build'

env:
  ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
  ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
  ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
  ANCHORECTL_FAIL_BASED_ON_RESULTS: false
  REGISTRY: ghcr.io

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Set IMAGE environmental variables"
        run: |
          # Convert GITHUB_REPOSITORY to lowercase for the image tag
          echo "IMAGE=${REGISTRY}/$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]'):${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Debug: IMAGE set to ${{ env.IMAGE }}" # Add for debugging

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build local container and push
        uses: docker/build-push-action@v3
        with:
          context: . # Explicitly set build context to current directory
          file: ./Dockerfile # Explicitly set Dockerfile path
          tags: ${{ env.IMAGE }}
          push: true
          load: false

  Anchore:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: "Set IMAGE environmental variables"
        run: |
          # Convert GITHUB_REPOSITORY to lowercase for the image tag
          echo "IMAGE=${REGISTRY}/$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]'):${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Latest anchorectl Binary
        run: |
          curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.6.0
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM and Push to Anchore
        run: |
          anchorectl image add --no-auto-subscribe --wait --from registry --dockerfile Dockerfile ${IMAGE}

      - name: Pull Vulnerability List
        run: |
          anchorectl image vulnerabilities ${IMAGE}

      - name: Pull Policy Evaluation
        run: |
          anchorectl image check --detail ${IMAGE}
