name: Anchore Enterprise Distributed Scan

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Build'

env:
  ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
  ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
  ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
  ANCHORECTL_FAIL_BASED_ON_RESULTS: false
  REGISTRY: ghcr.io

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Step to convert owner name to lowercase using Bash parameter expansion
      - name: Set Lowercase Owner Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "Debug: OWNER_LC set to ${{ env.OWNER_LC }}" # Add for debugging
        env:
          OWNER: '${{ github.repository_owner }}' # Pass the original owner name as an env var

      - name: Set IMAGE environmental variables
        run: |
          # Use the already lowercased owner from OWNER_LC
          # GITHUB_REPOSITORY (e.g., Sopuru/github_pipe) also contains the capitalized owner,
          # so we'll reconstruct the repo name part to ensure it's fully lowercase if needed.
          # The `tr` command is robust for the repository name itself.
          REPO_NAME_ONLY=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_ONLY=${REPO_NAME_ONLY}" >> $GITHUB_ENV
          echo "Debug: REPO_NAME_ONLY set to ${{ env.REPO_NAME_ONLY }}"

          echo "IMAGE=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME_ONLY }}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Debug: Final IMAGE set to ${{ env.IMAGE }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Container Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE }} # This will now use the fully lowercased IMAGE
          push: true

  Anchore:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      # Set Lowercase Owner Name again for consistency in this job
      - name: Set Lowercase Owner Name for Anchore Job
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: "Set IMAGE environmental variables for Anchore"
        run: |
          REPO_NAME_ONLY=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_ONLY=${REPO_NAME_ONLY}" >> $GITHUB_ENV
          
          echo "IMAGE=${{ env.REGISTRY }}/${{ env.OWNER_LC }}/${{ env.REPO_NAME_ONLY }}:${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Latest anchorectl Binary
        run: |
          curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.6.0
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM and Push to Anchore
        run: |
          anchorectl image add --no-auto-subscribe --wait --from registry --dockerfile Dockerfile ${IMAGE}

      - name: Pull Vulnerability List
        run: |
          anchorectl image vulnerabilities ${IMAGE}

      - name: Pull Policy Evaluation
        run: |
          anchorectl image check --detail ${IMAGE}
