name: Anchore Enterprise Distributed Scan

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Build'

env:
  ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
  ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
  ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
  ANCHORECTL_FAIL_BASED_ON_RESULTS: false
  REGISTRY: ghcr.io

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Set IMAGE environmental variables (Lowercase Owner and Repo)"
        run: |
          # Convert GITHUB_REPOSITORY_OWNER to lowercase
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWER=${REPO_OWNER_LOWER}" >> $GITHUB_ENV
          echo "Debug: REPO_OWNER_LOWER set to ${{ env.REPO_OWNER_LOWER }}"

          # Convert GITHUB_REPOSITORY to lowercase (specifically the 'repo_name' part, if needed)
          # GITHUB_REPOSITORY is typically "owner/repo-name"
          REPO_NAME_ONLY=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_ONLY=${REPO_NAME_ONLY}" >> $GITHUB_ENV
          echo "Debug: REPO_NAME_ONLY set to ${{ env.REPO_NAME_ONLY }}"

          # Construct the full image name with lowercase owner and repo name
          echo "IMAGE=${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.REPO_NAME_ONLY }}:${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Debug: Final IMAGE set to ${{ env.IMAGE }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Container Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE }}
          push: true

  Anchore:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: "Set IMAGE environmental variables (Lowercase Owner and Repo)"
        run: |
          # Ensure these are consistent with the Build job
          REPO_OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER_LOWER=${REPO_OWNER_LOWER}" >> $GITHUB_ENV

          REPO_NAME_ONLY=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME_ONLY=${REPO_NAME_ONLY}" >> $GITHUB_ENV

          echo "IMAGE=${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.REPO_NAME_ONLY }}:${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Latest anchorectl Binary
        run: |
          curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.6.0
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM and Push to Anchore
        run: |
          anchorectl image add --no-auto-subscribe --wait --from registry --dockerfile Dockerfile ${IMAGE}

      - name: Pull Vulnerability List
        run: |
          anchorectl image vulnerabilities ${IMAGE}

      - name: Pull Policy Evaluation
        run: |
          anchorectl image check --detail ${IMAGE}
