name: Anchore Enterprise Distributed Scan

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Build'

env:
  ANCHORECTL_URL: ${{ vars.ANCHORECTL_URL }}
  ANCHORECTL_USERNAME: ${{ vars.ANCHORECTL_USERNAME }}
  ANCHORECTL_PASSWORD: ${{ secrets.ANCHORECTL_PASSWORD }}
  ANCHORECTL_FAIL_BASED_ON_RESULTS: false
  REGISTRY: ghcr.io # Keep your registry here

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # *** NEW: Use docker/metadata-action to generate tags ***
      - name: Extract Docker metadata
        id: meta # Give this step an ID to reference its outputs
        uses: docker/metadata-action@v5 # Use a recent version
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }} # Base image name, metadata-action will lowercase this part
          tags: |
            type=ref,event=branch # e.g., main -> :main
            type=sha,format=long # e.g., :abcdef123456
            # You can add more tag types here if needed, e.g., semantic versioning if you use Git tags

      - name: Build and Push Container Image
        uses: docker/build-push-action@v6 # Use a recent version
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }} # Use the tags generated by metadata-action
          labels: ${{ steps.meta.outputs.labels }} # Optional: Use labels generated by metadata-action

  Anchore:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      # We still need the image name for Anchore.
      # The metadata-action directly outputs formatted tags, but for Anchore,
      # we often need a single, consistent tag (like the branch name or latest).
      # Let's derive it similarly to how metadata-action would, ensuring lowercase.
      - name: "Set IMAGE environmental variables for Anchore"
        run: |
          # The image tag typically follows the branch name for CI builds
          # Let's ensure the repo part is lowercased
          REPO_SLUG_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=${{ env.REGISTRY }}/${REPO_SLUG_LOWERCASE}:${{ github.ref_name }}" >> $GITHUB_ENV
          echo "Debug: Anchore IMAGE set to ${{ env.IMAGE }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Latest anchorectl Binary
        run: |
          curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.6.0
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate SBOM and Push to Anchore
        run: |
          anchorectl image add --no-auto-subscribe --wait --from registry --dockerfile Dockerfile ${IMAGE}

      - name: Pull Vulnerability List
        run: |
          anchorectl image vulnerabilities ${IMAGE}

      - name: Pull Policy Evaluation
        run: |
          anchorectl image check --detail ${IMAGE}
