# .github/workflows/vulnerability-scan.yml

name: Vulnerability Scan (Syft & Grype)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.12.0
        with:
          image: "alpine:latest"
          output-file: "sbom.spdx.json"
          upload-artifact: false

      - name: Display SBOM in Logs
        run: |
          echo "--- Generated SBOM (sbom.spdx.json) ---"
          cat sbom.spdx.json
          echo "----------------------------------------"

      - name: Scan SBOM with Grype
        uses: anchore/grype-action@v1
        with:
          sbom: "sbom.spdx.json"
          output-file: "grype-results.txt"
          output-template: "table"
          # Optional: Uncomment to fail on specific severity
          # fail-on-severity: "critical"

      - name: Display Grype Results in Logs
        run: |
          echo "--- Grype Scan Results ---"
          cat grype-results.txt
          echo "--------------------------"

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

      - name: Upload Grype Scan Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-results
          path: grype-results.txt
