name: Scan Alpine Image with Syft and Grype

on:
  push:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Pull alpine:latest
      run: docker pull alpine:latest

    - name: Generate SBOM with Syft
      run: syft alpine:latest -o table

    - name: Scan for vulnerabilities with Grype
      run: grype alpine:latest -o table
