env:
  SBOM_PATH: ./sbom.spdx.json

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.12.0
        with:
          image: "alpine:latest"
          output-file: ${{ env.SBOM_PATH }}
          upload-artifact: false

      - name: Confirm SBOM File Exists
        run: |
          echo "Listing workspace files..."
          ls -la
          echo "Checking SBOM path: $SBOM_PATH"
          test -f "$SBOM_PATH" && echo "SBOM file found." || (echo "SBOM not found!" && exit 1)

      - name: Display SBOM
        run: |
          echo "--- Generated SBOM ---"
          cat $SBOM_PATH
          echo "----------------------"

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype version

      - name: Scan SBOM with Grype
        run: |
          grype sbom:$SBOM_PATH -o table > grype-results.txt

      - name: Display Grype Results
        run: |
          cat grype-results.txt

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ${{ env.SBOM_PATH }}

      - name: Upload Grype Scan Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-results
          path: grype-results.txt
