# .github/workflows/vulnerability-scan.yml

name: Vulnerability Scan (Syft & Grype)

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main # Also trigger on pull requests targeting the main branch
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI

jobs:
  scan:
    runs-on: ubuntu-latest # Run the job on the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Generate SBOM with Syft
        # This step uses the anchore/sbom-action to generate the Software Bill of Materials (SBOM).
        # It will analyze the specified Docker image and output the SBOM in SPDX JSON format.
        uses: anchore/sbom-action@v0.12.0
        with:
          # Specify the Docker image to scan for SBOM generation.
          image: "alpine:latest"
          # Specify the output file for the SBOM. This will be created in the workspace root.
          output-file: "sbom.spdx.json"
          # Disable the action's internal artifact upload, as we will handle it manually.
          upload-artifact: false

      - name: Display Generated SBOM (JSON) in Workflow Log
        # This step reads the generated sbom.spdx.json file from the workspace root
        # and prints its content to the standard output,
        # allowing you to see the JSON SBOM directly in the logs.
        run: |
          echo "--- Generated SBOM (sbom.spdx.json) ---"
          cat sbom.spdx.json
          echo "----------------------------------------"

      - name: Scan SBOM for Vulnerabilities with Grype
        # This step uses the anchore/grype-action to scan the previously generated SBOM
        # for known vulnerabilities.
        uses: anchore/grype-action@v1 # Updated to a more common and stable version
        with:
          # Specify the SBOM file generated by the syft action as input for Grype.
          sbom: "sbom.spdx.json"
          # Specify the output file for Grype results in text format for readability.
          output-file: "grype-results.txt"
          # Specify the output format for Grype.
          output-template: "text"
          # Fail the build if any vulnerabilities of a certain severity are found.
          # Uncomment and adjust as needed (e.g., 'high', 'critical', 'medium').
          # fail-on-severity: "critical"

      - name: Display Grype Scan Results in Workflow Log
        # This step reads the generated grype-results.txt file from the workspace root
        # and prints its content to the standard output,
        # making the scan results visible directly in the GitHub Actions workflow logs.
        run: |
          echo "--- Grype Scan Results ---"
          cat grype-results.txt
          echo "--------------------------"

      - name: Upload SBOM as Artifact
        # This step uploads the generated SBOM as a workflow artifact.
        uses: actions/upload-artifact@v4
        with:
          name: project-sbom
          path: sbom.spdx.json # Path to the SBOM file generated by the previous step

      - name: Upload Grype Scan Results as Artifact
        # This step uploads the Grype scan results as a workflow artifact.
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-results
          path: grype-results.txt # Path to the Grype results file generated by the previous step
