# .github/workflows/vulnerability-scan.yml

name: Vulnerability Scan (Syft & Grype)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  SBOM_PATH: ./sbom.spdx.json
  IMAGE_NAME: alpine:latest

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.12.0
        with:
          image: ${{ env.IMAGE_NAME }}
          output-file: ${{ env.SBOM_PATH }}
          upload-artifact: false

      - name: Confirm SBOM File Exists
        run: |
          echo "Checking if SBOM file exists at $SBOM_PATH..."
          if [ ! -f "$SBOM_PATH" ]; then
            echo "Error: SBOM file not found!"
            find . -name "*.json"
            exit 1
          fi
          echo "SBOM file found."

      - name: Display Generated SBOM
        run: |
          echo "--- Generated SBOM ---"
          cat $SBOM_PATH
          echo "----------------------"

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          grype version

      - name: Scan SBOM with Grype
        run: |
          grype sbom:$SBOM_PATH -o table > grype-results.txt

      - name: Display Grype Scan Results
        run: |
          echo "--- Grype Scan Results ---"
          cat grype-results.txt
          echo "--------------------------"

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: ${{ env.SBOM_PATH }}

      - name: Upload Grype Scan Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-results
          path: grype-results.txt
