name: Debug SBOM Output Path

on:
  workflow_dispatch: # Trigger manually

jobs:
  debug-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.12.0
        with:
          image: "alpine:latest"
          output-file: "sbom.spdx.json"  # Declaring desired output name
          upload-artifact: false

      - name: Print Current Directory
        run: |
          echo "Current working directory:"
          pwd

      - name: List All JSON Files Recursively
        run: |
          echo "Searching for all .json files in the workspace..."
          find $GITHUB_WORKSPACE -name "*.json" || echo "No JSON files found."

      - name: Dump File Tree (Depth 3)
        run: |
          echo "Listing all files and folders (depth 3)..."
          command -v tree >/dev/null && tree -a -L 3 || find . -maxdepth 3
